# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Renta < Formula
  desc "Manage Renta ETL sources, destinations, pipelines and runs from the terminal"
  homepage "https://renta.im"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.4.0/renta_0.4.0_darwin_amd64.tar.gz"
      sha256 "de7cc7c01d1c93f1f63b92eec4fc45c5438c8ed9eb3e437835023a3566eedcac"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.4.0/renta_0.4.0_darwin_arm64.tar.gz"
      sha256 "2232cbe0f1b45f92f3df55ca5cc49827c8cf73e92bd2e3fbb9bf4ea97cd79466"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.4.0/renta_0.4.0_linux_amd64.tar.gz"
      sha256 "425b1b4df8846c5e9a5d9114a381bd06b0095363f244450a88f7df20283fc359"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.4.0/renta_0.4.0_linux_arm64.tar.gz"
      sha256 "58a89432d5202a0781ce0595edc1b2717179a9c674070c39dc273ed13feb66c3"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system bin/"renta", "version"
  end
end
