# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Renta < Formula
  desc "Manage Renta ETL connections, pipelines and runs from the terminal"
  homepage "https://renta.im"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.1.0/renta_0.1.0_darwin_amd64.tar.gz"
      sha256 "6e3bf454c5c5e456b2cdcf27586de760c9f48abf2b0cc692dbb1fcff8cb4f555"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.1.0/renta_0.1.0_darwin_arm64.tar.gz"
      sha256 "dba2404ca8549ebd1daf0f9884b8e929a3372b89767290aeb5e289dca67a0496"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.1.0/renta_0.1.0_linux_amd64.tar.gz"
      sha256 "5d9da1b5a0ef7df2536df407e77b2415bfb38e8ea713095164090d93689a7469"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.1.0/renta_0.1.0_linux_arm64.tar.gz"
      sha256 "481cb5c84bccb7abf2605a97539ad683164ac272d5f33ba075cabf88b71325cd"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system bin/"renta", "version"
  end
end
