# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Renta < Formula
  desc "Manage Renta ETL sources, destinations, pipelines and runs from the terminal"
  homepage "https://renta.im"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.3.0/renta_0.3.0_darwin_amd64.tar.gz"
      sha256 "0ae443170cde17b88fabab7424100fcde19f4544c15834b265786472dea16f9d"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.3.0/renta_0.3.0_darwin_arm64.tar.gz"
      sha256 "bec6c0c49a7d8167a5c42bc9458a4e96f16e223c3202bf9bb03f35fd99598030"

      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.3.0/renta_0.3.0_linux_amd64.tar.gz"
      sha256 "52a635fe8a390bfa4987a57f07f27393121386742f80d27fb7180a12d0d33452"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/renta-im/homebrew-tap/releases/download/v0.3.0/renta_0.3.0_linux_arm64.tar.gz"
      sha256 "25f67bafacb49b693f76a0eb8525f7f4be524c788fe36a56723ca338bc42f0b0"
      define_method(:install) do
        bin.install "renta"
        generate_completions_from_executable(bin/"renta", "completion")
        system bin/"renta", "man", "--dir", "man"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system bin/"renta", "version"
  end
end
